name: Build

on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: rust-stm32
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build F103
        run: cargo build --release --target thumbv7m-none-eabi --features stm32f103c8

      - name: Build F072
        run: cargo build --release --target thumbv6m-none-eabi --features stm32f072c8

      - name: Pack tools
        run: |
          tar -czf scripts.tar.gz -C scripts hid_code.py setup-key.py requirements.txt README.md

      - name: Create binary dists
        run: |
          arm-none-eabi-objcopy -O binary target/thumbv7m-none-eabi/release/one-button-keyboard one-button-keyboard-f103.bin
          arm-none-eabi-objcopy -O binary target/thumbv6m-none-eabi/release/one-button-keyboard one-button-keyboard-f072.bin

      - uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - uses: akkuman/gitea-release-action@v1
        with:
          name: v${{ steps.read_version.outputs.value }}
          body: This is an automatic ${{ steps.read_version.outputs.value }} release!
          prerelease: true
          files: |
            one-button-keyboard-f103.bin
            one-button-keyboard-f072.bin
            scripts.tar.gz
