name: Pull Request Workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - "*/*"

jobs:
  build-windows:
    runs-on: rust-stm32
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: cargo build --release
