name: Build

on: 
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install compiler
        run: rustup target add thumbv7m-none-eabi

      - name: Install tools
        run: |
          cargo install cargo-binutils
          rustup component add llvm-tools          

      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: cargo build --release

      - name: Pack tools
        run: |
          tar -czf scripts.tar.gz -C scripts hid_code.py setup-key.py requirements.txt README.md

      - name: Create binary dist
        run: rust-objcopy -O binary target/thumbv7m-none-eabi/release/one-button-keyboard one-button-keyboard.bin

      - uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.read_version.outputs.value }}
          body: This is an automatic ${{ steps.read_version.outputs.value }} release!
          prerelease: true
          files: |
            one-button-keyboard.bin
            scripts.tar.gz 
