name: Pull Request Workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - "*/*"

jobs:
  build-windows:
    runs-on: ubuntu-24.04
    steps:
      - name: Install compiler
        run: rustup target add thumbv7em-none-eabihf
        
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: cargo build --release