name: Pull Request Workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - "*/*"

jobs:
  build-windows:
    runs-on: ubuntu-24.04
    steps:
      - name: Install compiler
        run: rustup target add thumbv7m-none-eabi
        
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build F103
        run: cargo build --release --target thumbv7m-none-eabi --features stm32f103c8

      - name: Build F072
        run: cargo build --release --target thumbv6m-none-eabi --features stm32f072c8
